### ISSUE TITLE
Create input option to mask env variables

### ISSUE THREAD

**Issue by channingko-madden** [dcarbone/yaml-to-env-action#2]
Hello! 

Firstly thank you for this github action! I wanted to suggest creating an optional boolean input that can be set by a user to [mask the env variable](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#example-masking-an-environment-variable) value that this action creates. I think it would be very convenient, and I'm not aware of a easy way to do this in a step after this action runs without the environment variable values already getting exposed within the logs.

**Comment by dcarbone** [comment]
Hey @channingko-madden, I've whipped up a branch with this feature: https://github.com/dcarbone/yaml-to-env-action/pull/3

Could you please test that this update suites your needs?

**Comment by channingko-madden** [comment]
Hi @dcarbone thank you for taking this on so quickly. I created another PR #4 to merge with the branch you created, to add support for masking multi-line values which I need for my use case.

**Comment by dcarbone** [comment]
Hey @channingko-madden, I've released v3 with these changes in it.  Thank you for your contribution and please let me know if you run into any other issues!

**Comment by channingko-madden** [comment]
@dcarbone Thank you for releasing v3 I really appreciate it!
