### ISSUE TITLE
YQ install action is (probably) receiving an empty YQ version and so not using its default value

### ISSUE THREAD

**Issue by felipegr** [dcarbone/yaml-to-env-action#5]
Hi @dcarbone,

Firstly, thank you for this action, it is very useful. I don't know if something changed since the last weekend (Nov 16th or 17th 2024) but I can see that the `dcarbone/install-yq-action@v1` action that is running inside step `install-yq` is failing. From what I could see in the logs of a run I believe the YQ version, that is being informed to the install action as `version: '${{ inputs.yq-version }}'`, is actually being informed as an empty string, so action `dcarbone/install-yq-action` is not using the default value (that is `"v4.44.3"`).

Here are the logs from my run:
```
Run dcarbone/yaml-to-env-action@v3
Run if ! [ -f 'config.yaml' ]; then
Run '/home/runner/k8s/index.js'
Run dcarbone/install-yq-action@v1
Run _yq_bin="$(which yq)"
Run '/home/runner/k8s/index.js'
Run $GITHUB_ACTION_PATH/scripts/unixish.sh
Run '/home/runner/k8s/index.js'
Prep
Downloading yq
  Src: https://github.com/mikefarah/yq/releases/download//yq_linux_amd64.tar.gz
  Dst: /__w/_temp/yq_linux_amd64.tar.gz
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  100     9  100     9    0     0     47      0 --:--:-- --:--:-- --:--:--    47
Expanding archive
  
  gzip: stdin: not in gzip format
  tar: Child returned status 1
  tar: Error is not recoverable: exiting now
  Error: Error: failed to run script step: command terminated with non-zero exit code: error executing command [sh -e /__w/_temp/2adbfa40-a5c3-11ef-ae75-136bf75caa76.sh], exit code 2
  Error: Process completed with exit code 1.
  Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
```

As you can see the url being curled is `https://github.com/mikefarah/yq/releases/download//yq_linux_amd64.tar.gz`, which is wrong.

Do you believe you could fix this issue, please?

Thanks!

**Comment by dcarbone** [comment]
@felipegr Absolutely, apologies for that!  I'm updating install-yq-action and this action to account for this.

**Comment by dcarbone** [comment]
@felipegr: I've released https://github.com/dcarbone/yaml-to-env-action/releases/tag/v3.0.1, which uses an updated version of install-yq-action that handles empty version input values.

Please let me know if you run into any more issues!

**Comment by felipegr** [comment]
Thank you! I will let you know.
